### ISSUE TITLE
entryComponents Problem

### ISSUE THREAD

**Issue by MurhafSousli** [dherges/ng-packagr#583]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

My module depends on the overlay from `@angular/cdk`, some components are declared in `entryComponents` in my module.

The package builds successfully, but when I test the dist files in a new empty project, it fails

**ng serve**
```
ERROR in TypeError: Cannot read property 'assertNoMembers' of undefined
    at AotSummaryResolver.resolveSummary ({PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:31928:22)
    at CompileMetadataResolver._loadSummary ({PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:14709:66)
    at CompileMetadataResolver._getEntryComponentMetadata ({PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:15739:66)
    at {PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:15207:72
    at Array.map (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata ({PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:15207:18)
    at CompileMetadataResolver.getNgModuleSummary ({PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:15041:52)
    at {PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:15129:72
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata ({PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:15114:49)
    at visitLazyRoute ({PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:29937:104)
    at AotCompiler.listLazyRoutes ({PATH-TO-PROJECT}\node_modules\@angular\compiler\bundles\compiler.umd.js:29905:20)
    at AngularCompilerProgram.listLazyRoutes ({PATH-TO-PROJECT}\node_modules\@angular\compiler-cli\src\transformers\program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes ({PATH-TO-PROJECT}\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools ({PATH-TO-PROJECT}\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:248:66)
    at Promise.resolve.then.then ({PATH-TO-PROJECT}\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:571:50)
```
If I make any tiny change and save, it recompile then it works!

**ng serve --aot**
```
ERROR in Error: Unexpected value 'undefined' declared by the module 'GalleryModule in {PATH-TO-PROJECT}/dist/ng-gallery.d.ts'
```
The error does not go if I make a change with `--aot`

_I tested the UMD bundle in a plunkr and it works well_

---

After debugging more, I found out that it is caused by the `entryComponents` I use in the module. when I commented it, it worked!

#### How To Reproduce

A normal module that uses `entryComponents`

build `npm run packagr`

then try to use it in an empty project

`ng serve` and `ng serve --aot`

#### Expected behavior

Should work with `entryComponents`

#### Version Information

```
ng-packagr: rc.13
@angular/*: 5.0.0
typescript: 2.4.2
```

**Comment by dherges** [comment]
hi, can you give access to a repro?

**Comment by MurhafSousli** [comment]
Thanks, @dherges Can't tell what was wrong, but the issue is solved after upgrading to v2.0.0

**Comment by deephakdd** [comment]
@MurhafSousli  : I am facing the same issue still . my ng-packagr version is 2.0.0.

Can you tell if you have made any changes to the way the entryComponent is declared or the module hosting is exported
